---
title: "Regulamin Zajęć"
output:
  pdf_document: default
  word_document: default
header-includes: \usepackage[polish]{babel}
---

Przedmiot: Programowanie strukturalne

Rodzaj zajęć: wykład

Kierunek: Informatyka

Specjalność: Informatyka ogólna, Inżynieria systemów informatycznych

Poziom studiów: studia pierwszego stopnia

Rodzaj studiów: studia stacjonarne

Rok i semestr: rok I, semestr drugi

Rok akademicki: 2020/2021

Prowadzący: dr Piotr Jastrzębski, piotr.jastrzebski@uwm.edu.pl

Liczba punktów ECTS: 6

## 1. Wymagana forma uczestnictwa w zajęciach
Od uczestników wymagana jest obecność na wykładach.

## 2. Cele kształcenia.

Opanowanie paradygmatu programowania strukturalnego i jego rozpoznawanie na tle innych paradygmatów.
Umiejętność stosowania programowania strukturalnego w programach małej i średniej wielkości.

## 3. Efekty kształcenia.

**Wiedza**

* Student zna konstrukcje programistyczne omawiane na wykładzie: typy strukturalne, typy wskaźnikowe,
wskaźniki do struktur, instrukcje alokacji i dealokacji obiektów typów strukturalnych, relację między
deklarowaniem wskaźnika a instrukcją alokacji obiektu.


**Umiejętności**

* Student potrafi napisać program z wykorzystaniem paradygmatu strukturalnego. Student rozumie znaczenie
właściwej struktury kodu.
* Student potrafi przeprowadzić dekompozycję funkcjonalną zadania i ustrukturyzować kod tworzonego
programu


**Kompetencje społeczne**

* Student docenia rolę precyzji w formułowaniu problemów.
* Student jest świadomy konieczności ciągłego doskonalenia swoich umiejętności programistycznych w
trakcie swojego przyszłego rozwoju zawodowego.

## 4. Literatura.

1. Richard Resese, Wskaźniki w języku C. Przewodnik, wyd. Helion, 2014.
2. Stephen Prata, Język C. Szkoła programowania, wyd. Helion, 2006.
3. Stephen G. Kochan, Język C. Kompendium wiedzy. Wydanie IV, wyd. Helion, 2015.
4. Marek Tłuczek, Programowanie w języku C. Ćwiczenia praktyczne. Wydanie II, wyd. Helion, 2011.
5. Zed A. Shaw, Programowanie w C. Sprytne podejście do trudnych zagadnień, których wolałbyś unikać (takich jak język
C), wyd. Helion, 2016.



## 5. Sposób bieżącej kontroli wyników nauczania.

Brak.

## 6. Egzamin

Egzamin odbędzie się w formie komputerowej. Na egzaminie studenci dostaną klika zadań programistycznych, np.: samodzielne napisanie kodu, uzupełnienie kodu by działał poprawnie, propozycja algorytmu do
wybranego zagadnienia. Wyniki zostaną ogłoszone w ciągu 7 dni od daty egzaminu w systemie USOS. Terminy egzaminów zostaną ustalone w porozumieniu ze studentami na jednym z wykładów i będą opublikowane na stronie www prowadzącego zajęcia. Warunkiem przystąpienia do egzaminu jest uzyskanie pozytywnej oceny z ćwiczeń. Egzamin realizowany w trybie zdalnym będzie wymagał włączonej kamery i udostępnienia ekranu. Jego przebieg może zostać utrwalony.

## 7. Zasady ustalania oceny z egzaminu.

Ocena z egzaminu będzie obliczana wg poniższego wzoru:

* 0% - 50% punktów - ocena niedostateczna (2,0)
* 51% - 60% punktów - ocena dostateczna (3,0)
* 61% - 70% punktów - ocena dostateczna plus (3,5)
* 71% - 80% punktów - ocena dobra (4,0)
* 81% - 90% punktów - ocena dobra plus (4,5)
* 91% - 100% punktów - ocena bardzo dobra (5,0)


## 8. Możliwość korzystania z materiałów pomocniczych podczas zaliczenia.
W trakcie egzaminu można korzystać ze wszystkich materiałów, bez komunikacji z innymi osobami. Po egzaminie może nastąpić ustna video-weryfikacja samodzielności rozwiązań.

## 9. Zasada ustalania oceny końcowej zaliczenia przedmiotu.
Zaliczenie wykładu będzie przyznane tym uczestnikom zajęć, którzy otrzymają pozytywną ocenę z ćwiczeń oraz pozytywną ocenę z egzaminu. Oceną końcową jest ocena za egzamin. Studenci, którzy uzyskali ocenę bardzo dobrą (5,0) z ćwiczeń, zostaną zwolnieni z egzaminu z oceną końcową bardzo dobry (5,0).

## 10. Zasady usprawiedliwiania nieobecności na zajęciach.

Nieobecności na zajęciach będą usprawiedliwiane na podstawie usprawiedliwień pisemnych poświadczonych odpowiednim podpisem (ew. brak podpisu musi wynikać z przepisów szczególnych). Informacja o studentach, których liczba nieusprawiedliwionych nieobecności przekracza 3, zostanie przesłana do odpowiedniego dziekanatu.

## 11. Konsultacje.
Aktualne terminy konsultacji dostępne są w systemie USOS i na stronie prowadzącego zajęcia.


Ostatnia aktualizacja pliku: `r Sys.time()`.






